'use strict';

// tests for list-products
// Generated by serverless-jest-plugin

const mod = require('../../src/api/products');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'list' });

describe('list-products function', () => {
  const products = require('../fixtures/fake-products.json');

  beforeAll((done) => {
    done();
  });

  it('returns a list of products', async () => {
    const response = await wrapped.run({});
    expect(response).toBeDefined();
    const body = JSON.parse(response.body);
    expect(body).toBeDefined();
    expect(body.products).toEqual(products);
  });

  it('returns limited list when limit param is provided', async () => {
    const limit = 1;
    const response = await wrapped.run({ queryStringParameters: { limit } });
    const body = JSON.parse(response.body);
    expect(body.products.length).toBe(limit);
  });
});
